version: '3'
services:
  dbmate_up:
    image: 'ghcr.io/amacneil/dbmate:latest'
    env_file:
      - .env.local
    environment:
      - DBMATE_MIGRATIONS_DIR=/db/migrations
      - DBMATE_SCHEMA_FILE=/db/schema/schema.sql
      - DBMATE_WAIT=true
    command: ["up"]
    volumes:
      - "./autoredial:/db"
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
