version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 50051:50051
    depends_on:
      - db
    restart: always

  grpcui:
    image: 'wongnai/grpcui:latest'
    env_file:
      - .env
    environment:
      - GRPCUI_SERVER=server:50051
      - GRPCUI_PORT=8080
    ports:
      - 8080:8080
    command: ["sh", "-c", "sleep 10; /usr/local/scripts/start.sh"]
    depends_on:
      - server
      - db
      - pgweb

  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  pgweb:
    image: 'sosedoff/pgweb:latest'
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8081:8081
    command: ["sh", "-c", "sleep 10; /usr/bin/pgweb --bind=0.0.0.0 --listen=8081"]
