version: '3'
services:
  dbmate_up:
    image: 'ghcr.io/amacneil/dbmate:latest'
    environment:
      - DATABASE_URL=postgres://postgres:e8a48653851e28c69d0506508fb27fc5@db:5432/postgres?sslmode=disable
      - DBMATE_MIGRATIONS_DIR=/db/migrations
      - DBMATE_SCHEMA_FILE=/db/schema/schema.sql
      - DBMATE_WAIT=true
    command: ["up"]
    volumes:
      - "./autoredial:/db"
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
