# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import metric_pb2 as api_dot_v1_dot_metric__pb2


class MetricStoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetric = channel.unary_unary(
                '/api.v1.MetricStoreService/GetMetric',
                request_serializer=api_dot_v1_dot_metric__pb2.GetMetricRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_metric__pb2.GetMetricResponse.FromString,
                )
        self.PutMetric = channel.unary_unary(
                '/api.v1.MetricStoreService/PutMetric',
                request_serializer=api_dot_v1_dot_metric__pb2.PutMetricRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_metric__pb2.PutMetricResponse.FromString,
                )
        self.DeleteMetric = channel.unary_unary(
                '/api.v1.MetricStoreService/DeleteMetric',
                request_serializer=api_dot_v1_dot_metric__pb2.DeleteMetricRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_metric__pb2.DeleteMetricResponse.FromString,
                )


class MetricStoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetric,
                    request_deserializer=api_dot_v1_dot_metric__pb2.GetMetricRequest.FromString,
                    response_serializer=api_dot_v1_dot_metric__pb2.GetMetricResponse.SerializeToString,
            ),
            'PutMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.PutMetric,
                    request_deserializer=api_dot_v1_dot_metric__pb2.PutMetricRequest.FromString,
                    response_serializer=api_dot_v1_dot_metric__pb2.PutMetricResponse.SerializeToString,
            ),
            'DeleteMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMetric,
                    request_deserializer=api_dot_v1_dot_metric__pb2.DeleteMetricRequest.FromString,
                    response_serializer=api_dot_v1_dot_metric__pb2.DeleteMetricResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.MetricStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetricStoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.MetricStoreService/GetMetric',
            api_dot_v1_dot_metric__pb2.GetMetricRequest.SerializeToString,
            api_dot_v1_dot_metric__pb2.GetMetricResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.MetricStoreService/PutMetric',
            api_dot_v1_dot_metric__pb2.PutMetricRequest.SerializeToString,
            api_dot_v1_dot_metric__pb2.PutMetricResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.MetricStoreService/DeleteMetric',
            api_dot_v1_dot_metric__pb2.DeleteMetricRequest.SerializeToString,
            api_dot_v1_dot_metric__pb2.DeleteMetricResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
